"""ResearchCrew — generated by the CrewAI Agent Designer.

Do not hand-edit this file if you plan to re-generate: rerun the designer
against your saved design (JSON) and re-export. Hand edits are welcome once
you fork the project.
"""

from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
from crewai_tools import SerperDevTool

@CrewBase
class ResearchCrew:
    """ResearchCrew — 2 agent(s), 2 task(s)."""

    agents_config = "config/agents.yaml"
    tasks_config = "config/tasks.yaml"

    @agent
    def researcher(self) -> Agent:
        return Agent(
            config=self.agents_config["researcher"],
            tools=[SerperDevTool()],
            verbose=False,
        )

    @agent
    def writer(self) -> Agent:
        return Agent(
            config=self.agents_config["writer"],
            verbose=True,
        )

    @task
    def research(self) -> Task:
        return Task(
            config=self.tasks_config["research"],
            tools=[SerperDevTool()],
        )

    @task
    def write_brief(self) -> Task:
        return Task(
            config=self.tasks_config["write_brief"],
            context=[self.research()],
        )

    @crew
    def crew(self) -> Crew:
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
            memory=False,
            cache=True,
        )


if __name__ == "__main__":
    result = ResearchCrew().crew().kickoff(inputs={})
    print(result)
