"""web_search — CAS-compatible SerperDevTool wrapper.

Google-style web search via Serper.dev. Requires SERPER_API_KEY in the runtime environment; no constructor args.

Generated by the CrewAI Agent Designer. Uploaded to Cloudera Agent Studio as
a tool template, this module wraps `crewai_tools.SerperDevTool`
so an agent inside CAS can call it without importing CrewAI directly.

Contract (imposed by Cloudera Agent Studio):
- `UserParameters` — the workflow author's configuration.
- `ToolParameters` — the arguments the agent supplies at each call.
- `run_tool(config, args)` — the implementation.
- `OUTPUT_KEY = "tool_output"` — the sentinel CAS greps for when parsing output.
- `__main__` block — CAS spawns the tool as a subprocess with `--user-params`
  and `--tool-params` as JSON strings.
"""

from typing import Optional
import argparse
import json

from pydantic import BaseModel, Field
from pydantic import BaseModel as StudioBaseTool  # noqa: F401 — CAS marker alias

from crewai_tools import SerperDevTool


class UserParameters(BaseModel):
    """Workflow-author configuration for SerperDevTool."""
    pass


class ToolParameters(BaseModel):
    """Runtime arguments the agent supplies at call time."""
    search_query: str = Field(
        ...,
        description="The search query.",
    )


OUTPUT_KEY = "tool_output"


def run_tool(config: UserParameters, args: ToolParameters):
    """Instantiate the wrapped CrewAI tool with `config`, then run it with `args`.

    Errors are caught and returned as a small dict so CAS's log parser always
    receives valid JSON on the OUTPUT_KEY line rather than a Python traceback.
    """
    try:
        constructor_kwargs = {
            k: v for k, v in config.model_dump().items() if v is not None
        }
        tool = SerperDevTool(**constructor_kwargs)
        call_kwargs = {
            k: v for k, v in args.model_dump().items() if v is not None
        }
        return tool.run(**call_kwargs)
    except Exception as e:  # noqa: BLE001 — surface every failure as data
        return {"status": "error", "error_message": str(e)}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="CAS tool wrapper for SerperDevTool."
    )
    parser.add_argument(
        "--user-params",
        required=True,
        help="JSON string with the workflow-author configuration.",
    )
    parser.add_argument(
        "--tool-params",
        required=True,
        help="JSON string with the agent's runtime arguments.",
    )
    cli_args = parser.parse_args()

    config = UserParameters(**json.loads(cli_args.user_params))
    params = ToolParameters(**json.loads(cli_args.tool_params))

    output = run_tool(config, params)
    print(OUTPUT_KEY, output)
